import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Akash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* If you want to use the Geist font via CDN, you can add this line: */}
        {/* <link rel="stylesheet" href="https://geists.vercel.app/font.css" /> */}
      </head>
      <body className="w-full h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}
